### ISSUE TITLE
No "Unlike" behaviour

### ISSUE THREAD

**Issue by ch3ckmat3** [fluttercandies/like_button#1]
Is there any way I can use it as a simple button, instead of a toggle button? I would like the user to be able to click the button for likes, but don't want them to click again to Unlikes, so the button will behave as a normal button, always showing animation for likes and incementing like counts, never decreasing like counts.

**Comment by zmtzawqlp** [comment]
@ch3ckmat3 please check it on version 0.1.4,it's ready on pub

**Comment by zmtzawqlp** [comment]
@ch3ckmat3 reopen it if you have any other problem

**Comment by ch3ckmat3** [comment]
How to use it?

**Comment by zmtzawqlp** [comment]
read readme or changelog ， 
![image](https://user-images.githubusercontent.com/16477333/59775892-826ea980-92e4-11e9-86a9-fb6828c8c61b.png)

**Comment by ch3ckmat3** [comment]
great, thanks :)
