### ISSUE TITLE
strange behaviour with like count widget

### ISSUE THREAD

**Issue by VickySalunkhe** [fluttercandies/like_button#12]
I noticed this issue

if like count is greater than 10 ex, 11, 12 etc...

two text widgets are shown
there are no errors shown nothing don't know what going wrong

if like count is less than 10 it works fine

you can refer the below image 

when setState() is called it gets back to normal but if someone interacts with It it once again reappears 

![WhatsApp Image 2019-10-09 at 4 18 23 PM](https://user-images.githubusercontent.com/37410248/66475518-1a211f00-eab1-11e9-85da-0a25f9a0e624.jpeg)

and support for changing background colour is also required as you can see now background is light grey 

please provide the solution as soon as possible as I am using this library in live app and users are facing this issue

**Comment by zmtzawqlp** [comment]
please provide runable demo to show your case.

**Comment by VickySalunkhe** [comment]
https://drive.google.com/file/d/15c3dqPNE9146FNqM8ZplOEiACLaukQCg/view?usp=drivesdk

You can view the video here.

**Comment by VickySalunkhe** [comment]
https://drive.google.com/file/d/15c3dqPNE9146FNqM8ZplOEiACLaukQCg/view?usp=drivesdk

You can view the video here.

**Comment by zmtzawqlp** [comment]
I need to know what code is causing this problem，i can't just think about it

**Comment by VickySalunkhe** [comment]
`class _PostLikeState extends State<PostLike> {
  @override
  Widget build(BuildContext context) {
    return Material(child: _likeButton());
  }

  Widget _likeButton() {
    return LikeButton(
      size: 26,
      isLiked: widget.post.likeStatus,
      likeBuilder: (bool isLiked) {
        return Icon(
          isLiked ? Icons.favorite : Icons.favorite_border,
          color: isLiked ? Colors.red : Colors.black54,
          size: widget.fontSize >= 24 ? widget.fontSize : 20,
        );
      },
      likeCount: widget.post.likeCount,
      countBuilder: (int count, bool isLiked, String text) {
        var color = Colors.black54;
        Widget result;
        result = InkWell(
          onTap: () =>
              Routes.launchLikesPage(context, widget.post.postID, "post"),
          child: Container(
            padding: EdgeInsets.only(
                left: widget.fontSize >= 24 ? 8.0 : 0.0,
                right: 6.0,
                top: 6.0,
                bottom: 6.0),
            child: Text(
              ConstantValues.getCountString(count),
              style: TextStyle(
                  color: color, fontSize: widget.fontSize >= 24 ? 14 : 11),
            ),
          ),
        );
        return result;
      },
      likeCountAnimationType: widget.post.likeCount < 1000
          ? LikeCountAnimationType.part
          : LikeCountAnimationType.none,
      onTap: (bool isLiked) {
        return onLikeButtonTap(isLiked, widget.post);
      },
    );
  }

  Future<bool> onLikeButtonTap(bool isLiked, Post post) {
    ///send your request here
    ///
    final Completer<bool> completer = new Completer<bool>();
    Timer(const Duration(milliseconds: 200), () {
      if (widget.post.likeStatus) {
        widget.post.likeStatus = !widget.post.likeStatus;
        widget.post.likeCount--;
        removeLike("post", widget.post.postID);
      } else {
        widget.post.likeCount++;
        widget.post.likeStatus = !widget.post.likeStatus;
        addLike("post", widget.post.postID);
      }

      // if your request is failed,return null,
      completer.complete(post.likeStatus);
    });
    return completer.future;
  }
}

addLike(String type, String postID) async {

}

removeLike(String type, String postID) async {

}`



this is the code im using

**Comment by VickySalunkhe** [comment]
I guess the problem is with **LikeCountWidgetBuilder** 
when i dont pass it likes are shown
but i want to customize somethings like font size and spacing and i guess thats why **LikeCountWidgetBuilder** is there for

**Comment by zmtzawqlp** [comment]
``` dart
countBuilder: (int count, bool isLiked, String text) {
                var color = Colors.grey;
                Widget result;

                result = Text(
                  text,
                  style: TextStyle(color: color),
                );
                return result;
              },
              likeCountPadding: EdgeInsets.only(top: 15.0),
              countDecoration: (Widget count) {
                return Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    count,
                    SizedBox(
                      width: 10.0,
                    ),
                    Text(
                      "loves",
                      style: TextStyle(color: Colors.indigoAccent),
                    )
                  ],
                );
              },
            ),
```


i think you need countDecoration

**Comment by VickySalunkhe** [comment]
no help same problem occurs when I add countDecoration code

**Comment by zmtzawqlp** [comment]
see clear,
don't use count to calculate text to show。 please take a look at demo

```
              countBuilder: (int count, bool isLiked, String text) {
                var color = Colors.grey;
                Widget result;

                result = Text(
                  text,
                  style: TextStyle(color: color),
                );
                return result;
              },
```

**Comment by VickySalunkhe** [comment]
does it support text append for million and thousand like
1k, 1m ?

i am using count as that function returns a text


some space is being added dont know how 
please look into it

![WhatsApp Image 2019-10-10 at 2 01 31 PM](https://user-images.githubusercontent.com/37410248/66552221-8e69ca00-eb66-11e9-9781-e7adfd966452.jpeg)

**Comment by VickySalunkhe** [comment]
that space issue was being caused because of padding in container i added for now its resolved

**Comment by zmtzawqlp** [comment]
please take a look at demo。。1k has demo

**Comment by zmtzawqlp** [comment]
countDecoration for background

**Comment by VickySalunkhe** [comment]
i am taling about changing the whole background including like icon as you can see in the image whole widget provided by the library passes light grey colour

**Comment by zmtzawqlp** [comment]
change whole background when like count is changing?

**Comment by VickySalunkhe** [comment]
no i want to change the background colour whole time

example my app them colour is white so will need to add every widget with background colour set to white 

i just tested with count of 1000,  9999, 10000   support of 1k is missing i guess

**Comment by zmtzawqlp** [comment]
does it work for you about background?
``` dart
   Container(
        child: LikeButton(),
        color: Colors.grey,
      );
```
999=>1k  is support transistion animation,please take a look at first like button demo.

**Comment by VickySalunkhe** [comment]
Above code helps for the background thankyou

but that support for count > 999
followed your like button demo too.

![WhatsApp Image 2019-10-10 at 2 44 27 PM](https://user-images.githubusercontent.com/37410248/66556188-65006c80-eb6d-11e9-9ed6-8fc06c286784.jpeg)

**Comment by AlexVincent525** [comment]
We noticed that your issue can't tell the specific bug/issue of this package, so plz be more specific and track only one problem per issue, thanks.
