### ISSUE TITLE
This does not seem to work on Flutter web

### ISSUE THREAD

**Issue by DeGerlash** [fluttercandies/like_button#14]
When attempting to draw a simple LikeButton using the LikeButton(likeCount:69) constructor, it throws the following error on web:

> Flutter Web does not support the blend mode: BlendMode.clear

Is this something I can resolve for the web or a library issue?

**Comment by zmtzawqlp** [comment]
flutter web doesn't support BlendMode.clear,  it's used to clear Circle

**Comment by DeGerlash** [comment]
Alright, so is there a workaround I can use or a fork that does support
this code on the web? It works great on mobile

Op do 17 okt. 2019 03:24 schreef zmtzawqlp <notifications@github.com>:

**Comment by zmtzawqlp** [comment]
i have no idea now, flutter web is preview version. it's about the engine。
you can change this code at your side, see what happen
