### ISSUE TITLE
No way to pass record_id to onLikeButtonTapped

### ISSUE THREAD

**Issue by AteqEjaz** [fluttercandies/like_button#23]
Hi,

I'm using following code mentioned here https://pub.dev/packages/like_button#how-to-use-it 
, it passes isLiked value on onTap:onLikeButtonTapped, But issue is how we can pass record_id we are getting from server to this method? As we need to pass back record_id to server when we Tap on this LikeButton.

Any thoughtS?

Thanks :)

**Comment by zmtzawqlp** [comment]
why don't you get from data ?

**Comment by AteqEjaz** [comment]
Hi,

Thanks for coming back to me shortly, Following is the list i'm creating from server data via API,

![image](https://user-images.githubusercontent.com/3421084/74389691-d48aaf00-4e20-11ea-84f5-a04ed7f46841.png)

if u see the first card i have placed LikeButton there, which works fine when i click on it - Now for adding that property into the user favourites i need to get property_id when i click on that 'Heart' (i.e Like button), Ca u please elaborate how can i accomplish  this?

Thanks so much :)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/flutter_candies_demo_library/blob/14c71d92ae78b9247fbfe3b54b0d949af0ba0576/lib/src/data/tu_chong_repository.dart#L11

**Comment by zmtzawqlp** [comment]
one likebutton one  data

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/flutter_candies_demo_library/blob/14c71d92ae78b9247fbfe3b54b0d949af0ba0576/lib/src/widget/item_builder.dart#L90

**Comment by AteqEjaz** [comment]
@zmtzawqlp  thanks so much, it worked here is my Working code 

----
          LikeButton(
            size: 40,
            onTap: (bool isLiked) {
              return onLikeButtonTap(isLiked, id);
            },
          ),
------

  Future<bool> onLikeButtonTap(bool isLiked, id) async{
    /// send your request here
    // final bool success= await sendRequest();
      print(!isLiked);
      print(id);
      return !isLiked;

    /// if failed, you can do nothing
    // return success? !isLiked:isLiked;

  }

Thanks again :)
