### ISSUE TITLE
No option provided to send multiple or extra params in callback

### ISSUE THREAD

**Issue by jakthegr8** [fluttercandies/like_button#25]
`typedef LikeWidgetBuilder = Widget Function(bool isLiked);`

As per the above the code/line `LikeWidgetBuilder` is allowing user to send multiple or extra params. Which is an issue

**Comment by zmtzawqlp** [comment]
why do you need do this

**Comment by lain-ke** [comment]
To know (for example) in a List witch item was liked

**Comment by zmtzawqlp** [comment]
you have data of list, why don't you save it ?

**Comment by lain-ke** [comment]
Just forget it, it's a suplicate of [#23](https://github.com/fluttercandies/like_button/issues/23) and it has been resolved.

**Comment by jakthegr8** [comment]
@lain-ke , Thanks for the duplicate issue link
