### ISSUE TITLE
Add likeCount param in countDecoration

### ISSUE THREAD

**Issue by rupertbulquerin** [fluttercandies/like_button#26]
Add `int likeCount` param in countDecoration property for us to know the real count and for us to do some logic depending on the like count.

```
   countDecoration: (Widget count, int likeCount) {
        return Row(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            count,
            SizedBox(width: 5),
            Text(
              likeCount > 1 ? "Likes" : "Like",
              style: TextStyle(color: white.withOpacity(0.7), fontSize: 12),
            ),
          ],
        );
      },
```

**Comment by zmtzawqlp** [comment]
like count is ready known from your side

**Comment by rupertbulquerin** [comment]
how and where? or how to get the count value from countDecoration property?

**Comment by zmtzawqlp** [comment]
why should we must get it from countDecoration ?  like count is from your data, you already know it .

**Comment by rupertbulquerin** [comment]
yeah and also im having a problem implementing provider in it.
