### ISSUE TITLE
Like status changing on listview scrolling

### ISSUE THREAD

**Issue by gyanpreetsingh1993** [fluttercandies/like_button#27]
Like status is changing its status and is not retaining it during scroll of a listview. This adversely affects  "like an article" functionality in terms of users perspective.

**Comment by zmtzawqlp** [comment]
I think you should save status by yourself.  
https://github.com/fluttercandies/flutter_candies_demo_library/blob/3c5b0e893b0f1885560efff8bc1698cde8a8cf86/lib/src/widget/item_builder.dart#L91

https://github.com/fluttercandies/flutter_candies_demo_library/blob/3c5b0e893b0f1885560efff8bc1698cde8a8cf86/lib/src/data/tu_chong_repository.dart#L14
