### ISSUE TITLE
Trouble with count grather than 9

### ISSUE THREAD

**Issue by OrlinAlvarado** [fluttercandies/like_button#28]
I have the following Code, but when I click the like button, 10 becomes in 1111 instead on 11.

[frases_options_widget.txt](https://github.com/fluttercandies/like_button/files/4672939/frases_options_widget.txt)

**Comment by leszekkrol** [comment]
Why this is closed? Bug still exists

**Comment by zmtzawqlp** [comment]
please provide runnable demo
