### ISSUE TITLE
Animation not playing when a bunch were pressed

### ISSUE THREAD

**Issue by ichitaka** [fluttercandies/like_button#30]
I really like the animation, but sadly it is not playing the animation if:

a) there are a bunch of the buttons on a single screen (like a ListView)
b) the animation was triggered a few times (around 10-12 times)

When the button is pressed, you will see the small version of the icon and then straight the big one without any bubbles and circle. I might investigate this issue in the next week further but wanted to ask first if anybody else has experienced this yet.

**Comment by zmtzawqlp** [comment]
run https://github.com/fluttercandies/extended_image/blob/master/example/lib/pages/photo_view_demo.dart

see like_button in list
