### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Overflow'. 

### ISSUE THREAD

**Issue by xiongdi9456** [fluttercandies/like_button#31]
/flutter/.pub-cache/hosted/pub.flutter-io.cn/like_button-0.2.0/lib/src/like_button.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'Overflow'.
                overflow: Overflow.visible,

```
    • Flutter version 1.19.0-2.0.pre.208 at /Users/xx/Documents/flutter
    • Framework revision bfe6d2f4e6 (16 hours ago), 2020-05-29 19:08:01 -0400
    • Engine revision 4d78121a11
    • Dart version 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)
```

**Comment by ethanwheatthin** [comment]
I am also getting this error when upgrading to the newest version of flutter. I downgraded to my project to v1.17.1 using the **flutter version v1.17.1** command and it worked again

**Comment by zmtzawqlp** [comment]
we wouldn't focus on Flutter master branch , api changes frequently

**Comment by leszekkrol** [comment]
Any update in that case?

Flutter is already up to date on channel dev
Flutter 1.23.0-4.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 83dd176777 (5 days ago) • 2020-09-22 12:04:44 -0700
Engine • revision 2abe69c608
Tools • Dart 2.10.0 (build 2.10.0-136.0.dev)

**Comment by zmtzawqlp** [comment]
i didn't see any problem in latest version
