### ISSUE TITLE
Animation Status Listener

### ISSUE THREAD

**Issue by clragon** [fluttercandies/like_button#35]
I am using this library to create an upvote and downvote button.

When the user upvotes while the downvote is liked, then the downvote has to be unliked. 
I use a `ValueListenableBuilder` around my `LikeButton` so I can rebuild it when changing the like status.

So my code looks something like this:
```
enum _VoteStatus {
  upvoted,
  unknown,
  downvoted,
}

ValueNotifier<_VoteStatus> voteStatus = ValueNotifier(_VoteStatus.unknown);

ValueListenableBuilder(
  valueListenable: voteStatus,
  builder: (context, value, child) {
    return LikeButton(
      isLiked: value == _VoteStatus.upvoted,
      likeBuilder: (bool isLiked) {
        return Icon(
          Icons.arrow_upward,
          color: isLiked
              ? Colors.deepOrange
              : Theme.of(context).iconTheme.color,
        );
      },
      onTap: (isLiked) async {
          tryVote(context, post, true);
          if (isLiked) {
            return false;
          } else {
            return true;
          }
      },
    );
  },
),

Future<void> tryVote(
    BuildContext context, Post post, bool upvote) async {
  voteStatus.value = client.votePost(post.id, upvote);
}
```

But depending on how long the client needs to request the new vote status from the server, the animation is interrupted.
I cannot await `tryVote` in `onTap` because then the status will be set before returning and the animation never plays.

Is there a way you could allow adding a status listener to the animation, to then set the vote status after the animation played?

**Comment by zmtzawqlp** [comment]
we don't need wait service request back.
1. failed, reset status 
2. success，do nothing

**Comment by clragon** [comment]
I don't wait for the service request.
But the service request can be faster than the animation and cut it off, which looks bad.

And I always need to set the status, 
because the other button which is linked with this one has to be set correctly,
and because some other things also depend on the status.

Setting the status inside the onTap will just disables the animation.
