### ISSUE TITLE
when i scroll up and down the like count move the back state.

### ISSUE THREAD

**Issue by kadnan0900** [fluttercandies/like_button#40]

**Comment by kadnan0900** [comment]
//Like Widget
  Widget _likeWidget(ChallengeModel challengeModel) {
    return LikeButton(
      onTap: (bool isLiked) async {
        feedRepository.postLikes(
            id: challengeModel.id.toString(),
            like: challengeModel.is_liked ? 0.toString() : 1.toString());
        return !isLiked;
      },
      isLiked: challengeModel.is_liked,
      likeCountPadding: const EdgeInsetsDirectional.only(start: 8),
      size: 22,
      circleColor: CircleColor(start: Colors.white, end: Colors.white),
      bubblesColor: BubblesColor(
        dotPrimaryColor: AppColors.brightSun,
        dotSecondaryColor: AppColors.brightSun,
      ),
      likeBuilder: (bool isLiked) {
        return SvgPicture.asset("assets/heart.svg",
            color: isLiked ? AppColors.brightSun : Colors.white);
      },
      likeCount: challengeModel.likes_count,
      countBuilder: (int count, bool isLiked, String text) {
        Widget result;
        if (count == 0) {
          result = Text(
            "0",
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          );
        } else
          result = Text(
            text,
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
          );
        return result;
      },
    );
  }

**Comment by zmtzawqlp** [comment]
ontap(isliked){
challengeModel.isliked=!isliked;
}

https://github.com/fluttercandies/like_button/issues/24

**Comment by kadnan0900** [comment]
Can you give me the proper solution of this problem ?

**Comment by zmtzawqlp** [comment]
onTap: (bool isLiked) async {
   /// save it by yourself
    challengeModel.likes_count =?;
},

**Comment by supidupicoder** [comment]
Hello,

the issue here is that
likeBuilder: (bool isLiked)

is called with the **initially** set value of isLiked. 

so if it was initially false, it will always be false when being rebuild, even if it was changed in an onTap action.

any solutions to this?
