### ISSUE TITLE
Button shows no reaction when invoking onTap via GlobalKey

### ISSUE THREAD

**Issue by tanzmeier** [fluttercandies/like_button#47]
I create a GlobalKey for each LikeButton and want to invoke it from another onTap event.

Thats the onTap event of the button:
`
key: _e.get('room')['globalKey'],
onTap: (liked) async{
   print('${liked}');
   return !liked;
},`

But when i invoke it like this, nothing happens
`final LikeButton lk = _e.get('room')['globalKey'].currentWidget;
 lk.onTap(false);`

So i see the print-output, but the button doesnt react at all.

Any idea, what i am doing wrong?

Thanks for your help

**Comment by zmtzawqlp** [comment]
please provide runnable demo

**Comment by tanzmeier** [comment]
`
class LikeButtonTest extends StatefulWidget {
  @override
  _LikeButtonTestState createState() => _LikeButtonTestState();
  final GlobalKey tmpKey = new GlobalKey(debugLabel: 'likeButton');
  bool isLiked = false;
}

class _LikeButtonTestState extends State<LikeButtonTest> {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      color: Colors.lightBlueAccent,
      child: Row(
        children: [
          Material(
            color: Colors.greenAccent,
            child: InkWell(
              onTap: () {
                print('invoked through onTap');
                final LikeButton lk = widget.tmpKey.currentWidget;
                lk.onTap(widget.isLiked);
              },
              child: Container(
                width: 50,
              ),
            ),
          ),
          LikeButton(
            //size: 30,
            key: widget.tmpKey,
            onTap: (liked) async {
              print('onTap of likeButton');
              widget.isLiked = !widget.isLiked;
              print('isLiked ${widget.isLiked}');
              return widget.isLiked;
            },
            isLiked: widget.isLiked,
            likeBuilder: (bool isLiked) {
              return Icon(
                Icons.check_circle_outline,
                color: isLiked ? Colors.green : Colors.grey,
                //size: buttonSize,
              );
            },
          ),
        ],
      ),
    );
  }
}
`

So, with this example you can tap the like Button directly, which works fine, or you can can tap the green Material-Button, which triggers the onTap-Function through the global key, which doesnt show any reaction.

**Comment by zmtzawqlp** [comment]
please take a look at demo carefully

**Comment by xSILENCEx** [comment]
`LikeButton.onTap(bool)` is just a callback method

```diff dart
- final GlobalKey tmpKey = new GlobalKey(debugLabel: 'likeButton');
+ final GlobalKey<LikeButtonState> tmpKey = GlobalKey<LikeButtonState>(debugLabel: 'likeButton');
```
- - -
```diff dart
- final LikeButton lk = widget.tmpKey.currentWidget;
- lk.onTap(widget.isLiked);
+ widget.tmpKey.currentState.onTap();
```

**Comment by tanzmeier** [comment]
Jesus, what a silly mistake...
Sorry for wasting your time guys, and thanks a lot for your help!
