### ISSUE TITLE
Bubble animation does not work after Flutter 2

### ISSUE THREAD

**Issue by armandojimenez** [fluttercandies/like_button#50]
Hi, 

I upgraded to flutter 2 and the null safety version of this package, and now the bubble animation does not work, it does not overflow outside the side, it all stay in a little box the size of the heart, any fix for this? If I downgrade to 1.0.4 it works again

**Comment by zmtzawqlp** [comment]
you mean animation is cropped?

**Comment by armandojimenez** [comment]
Exactly! The animation now does not show outside the icon, it’s cropped to the animation size

**Comment by armandojimenez** [comment]
Thanks! Issue fixed with latest version
