### ISSUE TITLE
Strange async behaviour

### ISSUE THREAD

**Issue by zaidkazi** [fluttercandies/like_button#51]
Hey guys great library but a question when i run the like count and isLiked from a stream and have the onTap trigger a change in the value on a remote server it breaks the animation any suggestion

 ontap:    Future<bool> flameToggle(bool isLiked) async {
      await context
          .read<FIreStoreDB>()
          .myDB
          .setContentLiked(!isLiked));
      return !isLiked;
    }

also i have the isLiked being set initially  if liked or not from the stream

`isLiked: mycontentModelStream.myContent.isLiked)`

the values update but no animations

**Comment by zaidkazi** [comment]
Reading closed issues i see #43 also had this issue in a stream builder

**Comment by zmtzawqlp** [comment]
could you provide a simple runable demo? i can't see clearly with little code for this problem.

**Comment by zaidkazi** [comment]
Will try to create something! Thanks

**Comment by Infinitism** [comment]
I had the same issue and this is how I solved it. 

Don't set the "isLiked" value but instead use the "likeBuilder" to render the correct widget based on "like" or "unlike" state as determined by the stream you are using. 

With this, whenever you "unlike" and "like" again, the animation will work. 

"isLiked" is only set for "initial" rendering. So when the stream value changes, the whole "like_button" gets re-rendered vs just switching the "state" of like.
