### ISSUE TITLE
Implementing NumberFormat.compact() on likeCount

### ISSUE THREAD

**Issue by LangRizkie** [fluttercandies/like_button#52]
How do we use NumberFormat.compact() on likeCount? if the number hits 10,000 its not shorten to 10k

**Comment by LangRizkie** [comment]
I did it, 

`
countDecoration: (count, likeCount) {
  return Text(NumberFormat.compact().format(likeCount));
},`

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/like_button/blob/b4b664d0c2cdc87911a9c20c875eaa401e17ec29/example/lib/pages/like_button_demo.dart#L49
