### ISSUE TITLE
animation stopped 

### ISSUE THREAD

**Issue by venky9885** [fluttercandies/like_button#54]
When i used async function inside onbutton tapped ,animation is stopped,i tried many times or it will show initial color of button not updating liked color

**Comment by venky9885** [comment]
My code
`` final GlobalKey<LikeButtonState> _globalKey = GlobalKey<LikeButtonState>();

  Future<bool> onLikeButtonTapped(bool isLiked) async {
    ///bool val = isLiked;
    print((!isLiked).toString());
    if (!isLiked) {
      //val = !val;
      // _globalKey.currentState.onTap();
      mod.addLikes(data.id);
      print("liked");
    } else {
      //val = !val;
      //_globalKey.currentState.onTap();
      print("notliked");
    }

    /// send your request here
    // final bool success= await sendRequest();

    /// if failed, you can do nothing
    // return success? !isLiked:isLiked;

    return !isLiked;
  }
LikeButton(
                        onTap: onLikeButtonTapped,
                        // key: _globalKey,
                        // onTap: (isLiked) {
                        //   if (isLiked == null) {
                        //     isLiked = true;
                        //     mod.addLikes(data.id);
                        //   } else {
                        //     isLiked = true;
                        //     print("No");
                        //   }
                        //   //return isLiked;
                        // },
                        size: 40,
                        circleColor: CircleColor(
                            start: Color(0xff00ddff), end: Color(0xff0099cc)),
                        bubblesColor: BubblesColor(
                          dotPrimaryColor: Color(0xff33b5e5),
                          dotSecondaryColor: Color(0xff0099cc),
                        ),
                        likeBuilder: (bool isLiked) {
                          return Icon(
                            Icons.favorite,
                            color: isLiked
                                ? Colors.deepPurpleAccent
                                : Colors.black,
                            size: 40,
                          );
                        },
                        likeCount:
                            int.parse(data.data()['likeCount'].toString()),
                        countBuilder: (int count, bool isLiked, String text) {
                          var color =
                              isLiked ? Colors.deepPurpleAccent : Colors.grey;
                          Widget result;
                          if (count == 0) {
                            result = Text(
                              " 0 ",
                              style: TextStyle(
                                  color: color, fontWeight: FontWeight.w700),
                            );
                          } else
                            result = Text(
                              text.toString(),
                              style: TextStyle(
                                  color: color, fontWeight: FontWeight.w700),
                            );

                          return result;
                        },
                      ),``

**Comment by zmtzawqlp** [comment]
please provide runnable demo

**Comment by venky9885** [comment]
https://user-images.githubusercontent.com/59081163/119432459-fe27cb00-bd31-11eb-958d-225097208e4e.mp4

**Its again getting back to initial postion**

**Comment by Snorchy** [comment]
In my case I solved it by updating a variable of the Widget. That way the `likeBuilder` rebuilds with that variable of the class and works. Otherwise the parameter is lost.

**Comment by venky9885** [comment]
Tell me how can I solve it

**Comment by Snorchy** [comment]
> 
> 
> Tell me how can I solve it

You could be more respectful and try to solve the issue with the information I provided, before giving orders to anyone. Also, I have nothing to do with this project, I'm just an internet user.

**Comment by schnausages** [comment]
> > Tell me how can I solve it
> 
> You could be more respectful and try to solve the issue with the information I provided, before giving orders to anyone. Also, I have nothing to do with this project, I'm just an internet user.

awe this was such an attractive plugin! super cool and friendly animation but this same thing happened to me. i even used the exact code from the pub.dev page and the animation and count doesnt update anymore.

was there a bad commit to this plugin that caused a bug?

**Comment by schnausages** [comment]
> Screenrecorder-2021-05-25-08-13-28-132.1.mp4
> 
> **Its again getting back to initial postion**

did you happen to find a solution? ive been tinkering around with setState and conditionals and I'm still having the same issue! I like this plugin but hopefully its not bugged

**Comment by zmtzawqlp** [comment]
no more info for this issue, reopen if provide runnable demo
