### ISSUE TITLE
Like ontap issue

### ISSUE THREAD

**Issue by dalton5** [fluttercandies/like_button#56]
Hi,

I would like to be able in the tap event to set the liked state and change the state of the button and then call my API.

It's to avoid lag time of API call.

`onTap: (statusLiked) async {
      // set Likebutton liked = statusLiked how to do it?
      return await callApi!(taped);
    },`

How can I do it?

**Comment by zmtzawqlp** [comment]
return ! statusLiked;

**Comment by dalton5** [comment]
if I return !statusLiked it will work however if I have an error in my API call I couldn't come back to the iniitial value. Because the return will have already been done. No?

**Comment by zmtzawqlp** [comment]
yes，but you  can rollback status if failed

**Comment by dalton5** [comment]
How?

Would you have an example?

Thanks,

**Comment by renealas** [comment]
Hey have the same problem, the issue is that the Animation doesn't work with the onTap.  my OnTap Code is this: 

`onTap: (isliked) async {
                    likeFuntion(
                      ctx: ctx,
                      like: isliked, //listing.isFavorite,
                      listing: listing,
                    );
                  },`

And my Like funtion is: 

`Future<bool> likeFuntion({
    bool like,
    BuildContext ctx,
    Listing listing,
  }) async {
    if (!like) {
      Provider.of<Listings2>(ctx, listen: false).addFavorite(listing);

      if (listing.listingType != 'Web') {
        DatabaseMethods().saveNotification(
          'favorited',
          listing.userId,
          houseImage: listing.photos.first,
          listingId: listing.id,
        );
      }
    } else {
      Provider.of<Listings2>(ctx, listen: false).removeFavorite(listing.id);
    }
    listing.toggleFavoriteStatus(listing);
    return !like;
  }`

It works on my Backend however the Animation is completely lost, any Ideas?

**Comment by renealas** [comment]
Sorry, I found how it will work, just added into the onTap of the Like button the return to the function, now the animation works again.

**Comment by arindammitra06** [comment]
> Sorry, I found how it will work, just added into the onTap of the Like button the return to the function, now the animation works again.

Thanks a lot. Animation works now by returning the function.
