### ISSUE TITLE
Not centered Icon when not using count

### ISSUE THREAD

**Issue by teceP** [fluttercandies/like_button#60]
Hi, 

Iam trying to use the like widget, without the like count.
When I put it into a CircleAvatar, the Icon is not centered correctly:

![image](https://user-images.githubusercontent.com/44495947/146808468-59602bcc-4984-4194-8604-2b2622e71e96.png)

Any chance to fix this?

Thanks in advance!

**Comment by OLIVIER-MULLER** [comment]
Hello. 

You have to reset **both** paddings. 

padding: EdgeInsets.zero,
likeCountPadding: EdgeInsets.zero,
