### ISSUE TITLE
Can we start animation without onTap ?

### ISSUE THREAD

**Issue by NaNostyle** [fluttercandies/like_button#65]
i d'like to know if the animation is tied to the ontap or to the isLiked parameter ?
I want to start the animation based on a boolean stored in the database.
I tried to tie the isLiked parameter to a value from my database, but only the color of the icon changes, the animation is not triggered

**Comment by razfazz** [comment]
i would be also interested to show an animation after page load

**Comment by Infinitism** [comment]
Same issue. Whenever the "isLiked" parameter is set, the animation stops working when going from "unlike" to "like".

**Comment by zmtzawqlp** [comment]
you can use postFrameCallback to get controller or likeCountController do any thing you want , more detail see demo
