### ISSUE TITLE
Enlarge clickable zone

### ISSUE THREAD

**Issue by OLIVIER-MULLER** [fluttercandies/like_button#67]
Thanks for your package... Beautiful. 

Is there something to enlarge clickable zone ? Or a method to implement a larger zone properly ?

Lot of app enlarge clickable zone because like buttons are above another clickable zones (Cards, pictures...). The goal is to avoid clicking on the photo.

![zone](https://user-images.githubusercontent.com/72737997/181729514-a4731061-ec15-4ebb-8c82-0bcdf409a585.jpg)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extra_hittest_area  this is my other package, maybe it will help

**Comment by OLIVIER-MULLER** [comment]
Thanks. I've used a bigger and transparent CircleAvatar. 

CircleAvatar(
                          backgroundColor:
                              ColorsClass.blackColor.withOpacity(0),
                          radius: 45,
                          child: LikeButton(
                            mainAxisAlignment: MainAxisAlignment.end,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            padding: const EdgeInsets.all(10),
                            likeCountPadding: EdgeInsets.zero,
                            onTap: onLikeButtonTapped,
                            size: 20,
                            circleColor: CircleColor(
                              start: ColorsClass.customGreen.shade200,
                              end: ColorsClass.customGreen,
                            ),
                            circleSize: 50,
                            bubblesColor: BubblesColor(
                              dotPrimaryColor: ColorsClass.customGreen.shade200,
                              dotSecondaryColor: ColorsClass.customGreen,
                            ),
                          ),
                        ),

**Comment by zmtzawqlp** [comment]
1.add key LikeButton
2.put LikeButton into a bigger container
3.when a bigger container ontap, call key.ontap
