### ISSUE TITLE
Animate counting text on changed value

### ISSUE THREAD

**Issue by RoyalCoder88** [fluttercandies/like_button#68]
Hi thanks for your great package, can you help me with animating counting text on changed **value** , how can we trigger the animation without tapping on the button? Thanks in advance!

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/like_button/blob/237ee3995644486185a0d62ca625901b92b63638/example/lib/pages/like_button_demo.dart#L294

**Comment by RoyalCoder88** [comment]
Hi, @zmtzawqlp thanks for your help, basically what I want to achieve is the animation text counting to play when the value number is updated from the server, for example, the user LIKED already the post, and other users like the same post, and my likedCounting values is auto-updated, in this situation I want to trigger the animation of the text counting only. 

Thanks, and keep up the good work!
