### ISSUE TITLE
[Discussions] 

### ISSUE THREAD

**Issue by Junesui** [fluttercandies/like_button#80]
### Content

源码这里不能设置一个 MainAxisSize.min 吗？ 还是有什么用意？
导致点击按钮以外的地方，也能触发 likebutton 的 ontap 

![image](https://user-images.githubusercontent.com/53398033/223656183-a234c2a7-e133-4697-bef0-e0262ebe2d0a.png)

代码：
![image](https://user-images.githubusercontent.com/53398033/223656498-aed7e420-3e3c-4561-96f0-d2d658e628f1.png)

**Comment by zmtzawqlp** [comment]
你说之外。是指30？ 这个要看父容器。
