### ISSUE TITLE
先改变数字  如果提交错误 返回原来数字   为什么报错?

### ISSUE THREAD

**Issue by simanlx** [fluttercandies/like_button#85]
### Platforms

dart

### Description

  var aaaa= false;
  Future<bool> likeMomentsOne(workMomentID,index) {
    ///send your request here

    aaaa=!aaaa;
    final Completer<bool> completer = new Completer<bool>();
    completer.complete(aaaa);
    aaaa=!aaaa;
    await Timer(const Duration(milliseconds: 500), () {
      print("dddll");
      // if your request is failed,return null,
      completer.complete(aaaa);

    });

    return completer.future;
  }

### My code

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:41:31)[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:41:31)

**Comment by zmtzawqlp** [comment]
Future already completed
