### ISSUE TITLE
Count Position

### ISSUE THREAD

**Issue by superakabo** [fluttercandies/like_button#9]
Is there a way to place the count text below the button.

**Comment by zmtzawqlp** [comment]
it's very strange, and what would you do with count up/down animation

**Comment by superakabo** [comment]
> it's very strange, and what would you do with count up/down animation

It's not strange at all. I want the label to be at the bottom as shown here [](https://drive.google.com/open?id=1EnoQFB8-pRItlr6OFGH8uGhFm9lTIMS5)

**Comment by zmtzawqlp** [comment]
you can put text below likebutton without animation

**Comment by superakabo** [comment]
I want it to animate and increment the count whenever some presses the like button

**Comment by superakabo** [comment]
> @superakabo done

Awesome. Thanks.

**Comment by superakabo** [comment]
Anyway position was spelt wrongly. You have countPostion instead of countPosition

**Comment by zmtzawqlp** [comment]
please check latest demo

**Comment by superakabo** [comment]
> please check latest demo

I mean instead of countPosition you omitted the i in position so it is now 'countPostion'
